Fix patch 2.01 + script compilation
WopsS/RED4ext pull request #31
Opened 2023-10-04 14:52 UTC by psiberx

Fixes script compilation when REDmod is used.

2023-10-05 15:08 UTC, alghaibb approved these changes
Wouldn't mind trying this out to see if it works

2023-10-05 18:22 UTC, Giotje commented
@psiberx do you have the updated files somehwere? i can't seem to build it for some reason

2023-10-05 18:23 UTC, extract commented
> do you have the updated files somehwere? i can't seem to build it for some reason

If you need the build files they are available in github actions

https://github.com/WopsS/RED4ext/actions

But be aware that it's not working yet.

2023-10-05 18:26 UTC, Cybersific commented
Following progress, good work guys

2023-10-05 19:00 UTC, HGinnerup requested changes
Build fails with `'RED4EXT_RUNTIME_2_01': undeclared identifier`

Replacing `(aVersion == RED4EXT_RUNTIME_2_01)` with `true`, still gets blocked by `Image::IsSupported()` returning false.

Making `Image::IsSupported()` always return true, makes the game attempt to load, but seemingly crashes when it gets to the first mod, though it may just be that ArchiveXL also needs to update something.

```
[2023-10-05 20:36:21.983] [RED4ext] [info] RED4ext (v0.0.0+master.d4b3262.20231005T180444Z) is initializing...
[2023-10-05 20:36:21.983] [RED4ext] [info] Game patch: 2.01
[2023-10-05 20:36:21.983] [RED4ext] [info] Product version: 2.01
[2023-10-05 20:36:21.983] [RED4ext] [info] File version: 3.0.74.63017
[2023-10-05 20:36:22.067] [RED4ext] [info] RED4ext has been successfully initialized
[2023-10-05 20:36:22.146] [RED4ext] [info] RED4ext is starting up...
[2023-10-05 20:36:22.146] [RED4ext] [info] Loading plugins...
[2023-10-05 20:36:22.147] [RED4ext] [info] Loading plugin from '[...]\Cyberpunk 2077\red4ext\plugins\ArchiveXL\ArchiveXL.dll'...
```

2023-10-05 19:15 UTC, extract commented on src/dll/Utils.cpp
> +    else if (aVersion == RED4EXT_RUNTIME_2_01)
you need the submodule updated with https://github.com/WopsS/RED4ext.SDK/pull/92 ... just wait.

2023-10-05 19:50 UTC, HGinnerup commented on src/dll/Utils.cpp
> +    else if (aVersion == RED4EXT_RUNTIME_2_01)
Sorry, you're right. Updated the submodule as well, and it seems to work.

2023-10-05 21:09 UTC, DuskDweller approved these changes

2023-10-07 09:02 UTC, WopsS approved these changes
Thanks!

2023-10-07 09:02 UTC, merged